# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('in_transit', 'In Transit'),
                    ('delivered', 'Delivered'),
                    ('failed', 'Failed'),
                ],
                default='processing',
                max_length=20,
            ),
        ),
    ]
