# Generated by Codex on 2026-05-15

from django.db import migrations, models


def sync_existing_order_delivery_statuses(apps, schema_editor):
    order_model = apps.get_model('orders', 'Order')
    delivery_model = apps.get_model('orders', 'Delivery')

    terminal_order_statuses = {'cancelled', 'return_requested', 'returned'}
    for delivery in delivery_model.objects.select_related('order').all():
        order = delivery.order
        if order.status in terminal_order_statuses and delivery.status != order.status:
            delivery.status = order.status
            delivery.is_completed = False
            delivery.delivered_at = None
            delivery.save(update_fields=['status', 'is_completed', 'delivered_at'])
            continue

        if delivery.status == 'in_transit' and order.status == 'processing':
            order.status = 'shipped'
            order.save(update_fields=['status'])
            continue

        if delivery.status == 'delivered' and order.status not in {
            'delivered',
            'return_requested',
            'returned',
            'cancelled',
        }:
            order.status = 'delivered'
            order.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('in_transit', 'In Transit'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                    ('return_requested', 'Return Requested'),
                    ('returned', 'Returned'),
                    ('failed', 'Failed'),
                ],
                default='processing',
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_existing_order_delivery_statuses, migrations.RunPython.noop),
    ]
