# Generated by Django 6.0.3 on 2026-05-15 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def merge_delivery_fields_into_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Delivery = apps.get_model('orders', 'Delivery')

    delivery_status_map = {
        'pending': 'pending',
        'processing': 'processing',
        'in_transit': 'in_transit',
        'delivered': 'delivered',
        'cancelled': 'cancelled',
        'failed': 'failed',
        'return_requested': 'delivered',
        'returned': 'delivered',
    }
    order_status_map = {
        'pending': 'pending',
        'processing': 'processing',
        'shipped': 'in_transit',
        'delivered': 'delivered',
        'cancelled': 'cancelled',
        'failed': 'failed',
        'return_requested': 'delivered',
        'returned': 'delivered',
    }

    deliveries_by_order = {
        delivery.order_id: delivery
        for delivery in Delivery.objects.all()
    }

    for order in Order.objects.all():
        delivery = deliveries_by_order.get(order.id)
        source_status = delivery.status if delivery else order.status
        normalized_status = delivery_status_map.get(source_status) or order_status_map.get(order.status, 'processing')

        if order.status == 'cancelled':
            normalized_status = 'cancelled'

        order.status = normalized_status
        if delivery:
            order.tracking_number = delivery.tracking_number
            order.delivery_address = delivery.delivery_address or order.delivery_address
            order.is_completed = delivery.is_completed
            order.dispatched_at = delivery.dispatched_at
            order.delivered_at = delivery.delivered_at
            order.delivery_notes = delivery.notes
        elif order.status == 'delivered':
            order.is_completed = True
            order.delivered_at = order.updated_at

        if normalized_status == 'delivered':
            order.is_completed = True
            if order.delivered_at is None:
                order.delivered_at = order.updated_at
        if normalized_status in {'pending', 'processing', 'in_transit', 'cancelled', 'failed'}:
            order.is_completed = False
            if normalized_status in {'pending', 'processing', 'cancelled', 'failed'}:
                order.delivered_at = None

        order.save(update_fields=[
            'status',
            'tracking_number',
            'delivery_address',
            'is_completed',
            'dispatched_at',
            'delivered_at',
            'delivery_notes',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delivery_customer_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(merge_delivery_fields_into_orders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manager_note', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'db_table': 'return_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_request_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
            options={
                'db_table': 'return_request_items',
            },
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
