# Generated by Django 6.0.3 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakerimage',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='sneakerimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='products/sneakers/'),
        ),
    ]
