# Generated by Codex on 2026-06-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_convert_us_sizes_to_eu'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE sneaker_sizes
                DROP CONSTRAINT IF EXISTS sneaker_sizes_sneaker_id_637b25ab_fk_sneakers_id;

                ALTER TABLE sneaker_sizes
                ADD CONSTRAINT sneaker_sizes_sneaker_id_637b25ab_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE sneaker_sizes
                DROP CONSTRAINT IF EXISTS sneaker_sizes_sneaker_id_637b25ab_fk_sneakers_id;

                ALTER TABLE sneaker_sizes
                ADD CONSTRAINT sneaker_sizes_sneaker_id_637b25ab_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
