# Generated by Codex on 2026-06-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sneaker_size_db_cascade'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE reviews
                DROP CONSTRAINT IF EXISTS reviews_sneaker_id_eccdc1c8_fk_sneakers_id;

                ALTER TABLE reviews
                ADD CONSTRAINT reviews_sneaker_id_eccdc1c8_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE reviews
                DROP CONSTRAINT IF EXISTS reviews_sneaker_id_eccdc1c8_fk_sneakers_id;

                ALTER TABLE reviews
                ADD CONSTRAINT reviews_sneaker_id_eccdc1c8_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
