# Generated by Django 6.0.3 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
