# Generated by Django 6.0.3 on 2026-04-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_size_and_stock_enforcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
