# Generated by Codex on 2026-06-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE cart_items
                DROP CONSTRAINT IF EXISTS cart_items_sneaker_id_b07c16b2_fk_sneakers_id;

                ALTER TABLE cart_items
                ADD CONSTRAINT cart_items_sneaker_id_b07c16b2_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE cart_items
                DROP CONSTRAINT IF EXISTS cart_items_size_id_b5945759_fk_sneaker_sizes_id;

                ALTER TABLE cart_items
                ADD CONSTRAINT cart_items_size_id_b5945759_fk_sneaker_sizes_id
                FOREIGN KEY (size_id)
                REFERENCES sneaker_sizes(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE cart_items
                DROP CONSTRAINT IF EXISTS cart_items_sneaker_id_b07c16b2_fk_sneakers_id;

                ALTER TABLE cart_items
                ADD CONSTRAINT cart_items_sneaker_id_b07c16b2_fk_sneakers_id
                FOREIGN KEY (sneaker_id)
                REFERENCES sneakers(id)
                DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE cart_items
                DROP CONSTRAINT IF EXISTS cart_items_size_id_b5945759_fk_sneaker_sizes_id;

                ALTER TABLE cart_items
                ADD CONSTRAINT cart_items_size_id_b5945759_fk_sneaker_sizes_id
                FOREIGN KEY (size_id)
                REFERENCES sneaker_sizes(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        ),
    ]
